### ISSUE TITLE
Modify how the data is sent to DOIS

### ISSUE THREAD

**Issue by lrochette** [electric-cloud/EC-Subject7#4]
The Subject-7 send data to the DOIS in a way like:

Date | Passed | Failed | Skipped
-- | -- | -- | --
11/1/2018 | 10 | 2 | 1
11/2/2018 | 12 | 1 | 0

However in order to allow a stack widget, the data should be  sent as:

Date | Count | Outcome
-- | -- | --
11/1/2018 | 10 | Passed
11/1/2018 | 2 | Failed
11/1/2018 | 1 | Skipped
11/2/2018 | 12 | Passed
11/2/2018 | 1 | Failed
11/2/2018 | 0 | Skipped

**Comment by chenx21** [comment]
Laurent,

I do not see any difference between the Subject-7 send and allow a stack widget the data. Can you explain a bit more on this modification or send out the document that I can refer to?

Thanks.

Gary Chen

**Comment by lrochette** [comment]
@chenx21 you are correct, it was a bad copy/paste

**Comment by lrochette** [comment]
The problem with that solution is that the data does not work in the RCC anymore so I won't fix it.
